/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Sandro
 */
public class Cadastro extends javax.swing.JInternalFrame {

    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTextField9 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        LabelPainel = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Sistema de Cadastro");
        setPreferredSize(new java.awt.Dimension(950, 480));
        getContentPane().setLayout(null);

        jButton2.setText("Salvar");
        getContentPane().add(jButton2);
        jButton2.setBounds(450, 430, 110, 32);

        jButton1.setText("Limpar Campos");
        getContentPane().add(jButton1);
        jButton1.setBounds(310, 430, 120, 32);
        getContentPane().add(jTextField9);
        jTextField9.setBounds(40, 340, 660, 70);
        getContentPane().add(jTextField8);
        jTextField8.setBounds(30, 220, 170, 30);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(660, 130, 180, 30);

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setText("OBS:");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(40, 320, 34, 17);

        jLabel15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel15.setText("Data Montagem:");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(650, 280, 120, 30);

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setText("Monitor:");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(260, 280, 59, 17);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setText("Teclado:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(580, 200, 110, 30);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setText("Mouse:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(300, 200, 52, 17);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("Estabilizador:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(440, 280, 120, 20);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("CD:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 270, 60, 30);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("Placa Mãe:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 190, 120, 30);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("HD:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(460, 200, 40, 20);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Memória:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(680, 100, 90, 30);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(450, 130, 190, 30);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Serial:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 100, 60, 30);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Processador");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(490, 100, 110, 20);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Nome de Máquina");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(600, 30, 126, 17);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Sistema Operacional:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(240, 100, 160, 30);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Setor:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(350, 20, 110, 30);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(30, 50, 310, 30);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(350, 50, 240, 30);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Nome Usuário:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 20, 140, 30);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(30, 130, 180, 30);

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(240, 130, 190, 30);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(600, 50, 270, 30);

        LabelPainel.setBackground(new java.awt.Color(255, 255, 204));
        LabelPainel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LabelPainel.setForeground(new java.awt.Color(255, 255, 204));
        getContentPane().add(LabelPainel);
        LabelPainel.setBounds(0, 0, 960, 470);

        setSize(new java.awt.Dimension(961, 494));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelPainel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
