/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.PopupMenu;

/**
 *
 * @author Sandro
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private PopupMenu Cadastro;

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelAreaPrincipal = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        jmenuCadastro = new javax.swing.JMenu();
        jmenuConsulta = new javax.swing.JMenu();
        jmenuRelatorio = new javax.swing.JMenu();
        jmenuImpressao = new javax.swing.JMenu();
        jmenuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Cadastro");

        javax.swing.GroupLayout PainelAreaPrincipalLayout = new javax.swing.GroupLayout(PainelAreaPrincipal);
        PainelAreaPrincipal.setLayout(PainelAreaPrincipalLayout);
        PainelAreaPrincipalLayout.setHorizontalGroup(
            PainelAreaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        PainelAreaPrincipalLayout.setVerticalGroup(
            PainelAreaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 409, Short.MAX_VALUE)
        );

        jmenuCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/novo usuario.png"))); // NOI18N
        jmenuCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmenuCadastroMouseClicked(evt);
            }
        });
        jmenuCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuCadastroActionPerformed(evt);
            }
        });
        jMenuBar2.add(jmenuCadastro);

        jmenuConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/consulta2.png"))); // NOI18N
        jmenuConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmenuConsultaMouseClicked(evt);
            }
        });
        jMenuBar2.add(jmenuConsulta);

        jmenuRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/relatorio.png"))); // NOI18N
        jmenuRelatorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmenuRelatorioMouseClicked(evt);
            }
        });
        jMenuBar2.add(jmenuRelatorio);

        jmenuImpressao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/print2.png"))); // NOI18N
        jmenuImpressao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmenuImpressaoMouseClicked(evt);
            }
        });
        jMenuBar2.add(jmenuImpressao);

        jmenuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botaosairpng.png"))); // NOI18N
        jmenuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmenuSairMouseClicked(evt);
            }
        });
        jMenuBar2.add(jmenuSair);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelAreaPrincipal)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PainelAreaPrincipal)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(928, 533));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmenuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmenuSairMouseClicked

        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jmenuSairMouseClicked

    private void jmenuCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuCadastroActionPerformed
        // Codig para aticionarl tela de cadastro na area interna 


    }//GEN-LAST:event_jmenuCadastroActionPerformed

    private void jmenuCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmenuCadastroMouseClicked
        Cadastro tc = new Cadastro();
        PainelAreaPrincipal.add(tc);
        tc.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jmenuCadastroMouseClicked

    private void jmenuConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmenuConsultaMouseClicked
        // TODO add your handling code here:
        Consulta tc = new Consulta();
        PainelAreaPrincipal.add(tc);
        tc.setVisible(true);
    }//GEN-LAST:event_jmenuConsultaMouseClicked

    private void jmenuRelatorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmenuRelatorioMouseClicked
        // TODO add your handling code here:
        Relatorio tc = new Relatorio();
        PainelAreaPrincipal.add(tc);
        tc.setVisible(true);
    }//GEN-LAST:event_jmenuRelatorioMouseClicked

    private void jmenuImpressaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmenuImpressaoMouseClicked
// TODO add your handling code here:
        Impressao tc = new Impressao();
        PainelAreaPrincipal.add(tc);
        tc.setVisible(true);

    }//GEN-LAST:event_jmenuImpressaoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane PainelAreaPrincipal;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu jmenuCadastro;
    private javax.swing.JMenu jmenuConsulta;
    private javax.swing.JMenu jmenuImpressao;
    private javax.swing.JMenu jmenuRelatorio;
    private javax.swing.JMenu jmenuSair;
    // End of variables declaration//GEN-END:variables
}
